export RSVN_ROOT=/Users/windstorm/Work/svn/
source ~/.git-completion.sh

alias ls='ls -GF'
alias ll='ls -alh'
alias la='ls -A'
alias l='ls -CF'
alias grep='grep --color=auto'

export HISTCONTROL=ignoreboth
export GOROOT=/Users/windstorm/Work/hg/go/
export GOPATH=/Users/windstorm/Work/golang/
export PS1="\u@\h:\W #\! \A \`if [ \$? == 0 ]; then echo \:\); else echo \:\(; fi\` "
shopt -s histappend
